package hospitalModel;
// Generated 28-Apr-2017 22:11:08 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Patientappointment generated by hbm2java
 */
public class Patientappointment  implements java.io.Serializable {


     private int appNo;
     private Receptionist receptionist;
     private Date appDate;
     private Date appTime;

    public Patientappointment() {
    }

	
    public Patientappointment(int appNo, Receptionist receptionist) {
        this.appNo = appNo;
        this.receptionist = receptionist;
    }
    public Patientappointment(int appNo, Receptionist receptionist, Date appDate, Date appTime) {
       this.appNo = appNo;
       this.receptionist = receptionist;
       this.appDate = appDate;
       this.appTime = appTime;
    }
   
    public int getAppNo() {
        return this.appNo;
    }
    
    public void setAppNo(int appNo) {
        this.appNo = appNo;
    }
    public Receptionist getReceptionist() {
        return this.receptionist;
    }
    
    public void setReceptionist(Receptionist receptionist) {
        this.receptionist = receptionist;
    }
    public Date getAppDate() {
        return this.appDate;
    }
    
    public void setAppDate(Date appDate) {
        this.appDate = appDate;
    }
    public Date getAppTime() {
        return this.appTime;
    }
    
    public void setAppTime(Date appTime) {
        this.appTime = appTime;
    }




}


