package hospitalModel;
// Generated 28-Apr-2017 22:11:08 by Hibernate Tools 4.3.1



/**
 * Room generated by hbm2java
 */
public class Room  implements java.io.Serializable {


     private String roomNo;
     private Nurse nurse;
     private Integer telExtNo;
     private Integer patientBedNo;
     private String username;

    public Room() {
    }

	
    public Room(String roomNo, Nurse nurse) {
        this.roomNo = roomNo;
        this.nurse = nurse;
    }
    public Room(String roomNo, Nurse nurse, Integer telExtNo, Integer patientBedNo, String username) {
       this.roomNo = roomNo;
       this.nurse = nurse;
       this.telExtNo = telExtNo;
       this.patientBedNo = patientBedNo;
       this.username = username;
    }
   
    public String getRoomNo() {
        return this.roomNo;
    }
    
    public void setRoomNo(String roomNo) {
        this.roomNo = roomNo;
    }
    public Nurse getNurse() {
        return this.nurse;
    }
    
    public void setNurse(Nurse nurse) {
        this.nurse = nurse;
    }
    public Integer getTelExtNo() {
        return this.telExtNo;
    }
    
    public void setTelExtNo(Integer telExtNo) {
        this.telExtNo = telExtNo;
    }
    public Integer getPatientBedNo() {
        return this.patientBedNo;
    }
    
    public void setPatientBedNo(Integer patientBedNo) {
        this.patientBedNo = patientBedNo;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }




}


